FROM docker.io/miyakz1192/eng_app_word_meaning:1
MAINTAINER miyakz1192 <miyakz1192@gmail.com>

ENV DEBIAN_FRONTEND=noninteractive

RUN  cd /english_study_app_word_meaning/eng_app_word_meaning ; git pull origin master ; bundle install

